


name: Build 


# This part tells GitHub to run the workflow only if:
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "vite-project/"


jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest


# It checks out your repo code.

# fetch-depth: 0 means it fetches full git history — required for SonarQube to analyze code changes effectively.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For better analysis


# Uses SonarCloud GitHub Action to run static code analysis on your project.
      - name: SonarQube Scan
        working-directory: ../../vite-project
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ./vite-project
          args: >-
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectVersion=1.0
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=./src
            -Dsonar.exclusions=/reportWebVitals.ts,/index.tsx
            -Dsonar.tests=./src
            -Dsonar.test.inclusions=/.test.tsx,/.test.ts
            -Dsonar.test.exclusions=/node_modules/,/.spec.ts,/.stories.tsx,/services/,coverage/**
            -Dsonar.language=ts
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info

        # Secrets used
        env:
        # A secret token stored securely in GitHub (used for authentication).
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          #  Identify your project and organization on SonarCloud.
          SONAR_PROJECT_KEY: pavithrachandran70_last
          SONAR_ORGANIZATION: pavithrachandran70




# This GitHub Actions workflow runs a SonarCloud scan whenever code is pushed to the master branch or a 
# PR affecting the vite-project/ is opened or updated. It checks out the code, runs a scan using SonarCloud,
#  and reports issues, code smells, bugs, and test coverage. It focuses only on the vite-project folder and uses proper includes/excludes
#  to control which files are analyzed.
