# sonar.projectKey=pavithrachandran70_components
# sonar.organization=pavithrachandran70
# sonar.host.url=https://sonarcloud.io


# sonar.projectVersion=1.0
# sonar.sourceEncoding=UTF-8

# sonar.sources=./src
# sonar.exclusions=/reportWebVitals.ts,/index.tsx

# sonar.tests=./src
# sonar.test.inclusions=/.test.tsx,/.test.ts
# sonar.test.exclusions=/node_modules/,/.spec.ts,/.stories.tsx,/services/,coverage/**

# sonar.language=ts
# sonar.javascript.lcov.reportPaths=./coverage/lcov.info 









name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "vite-project/"

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For better analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ./vite-project
          args: >-
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectVersion=1.0
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=./src
            -Dsonar.exclusions=/reportWebVitals.ts,/index.tsx
            -Dsonar.tests=./src
            -Dsonar.test.inclusions=/.test.tsx,/.test.ts
            -Dsonar.test.exclusions=/node_modules/,/.spec.ts,/.stories.tsx,/services/,coverage/**
            -Dsonar.language=ts
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
            
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: pavithrachandran70_last
          SONAR_ORGANIZATION: pavithrachandran70



